// 51.
importjava.util.Scanner;
publicclassLinearSearch{
publicstaticvoidmain(String[]args){
Scannerinput=newScanner(System.in);
System.out.print("Enterthenumberofelementsinthearray:");
intn=input.nextInt();
int[]arr=newint[n];
System.out.println("Entertheelementsofthearray:");
for(inti=0;i<n;i++){
arr[i]=input.nextInt();
}
System.out.print("Entertheelementtosearchfor:");

intsearchElement=input.nextInt();
booleanfound=false;
intindex=-1;
for(inti=0;i<n;i++){
if(arr[i]==searchElement){
found=true;
index=i;
break;
}
}
if(found){
System.out.println(searchElement+"foundatindex"+index);
}else{
System.out.println(searchElement+"notfoundinthearray.");
}
}
}