// 52.
importjava.util.Scanner;
publicclassBinarySearch{
publicstaticvoidmain(String[]args){
Scannerinput=newScanner(System.in);
System.out.print("Enterthenumberofelementsinthesortedarray:");
intn=input.nextInt();
int[]arr=newint[n];
System.out.println("Enterthesortedelementsofthearray:");
for(inti=0;i<n;i++){
arr[i]=input.nextInt();
}
System.out.print("Entertheelementtosearchfor:");
intsearchElement=input.nextInt();
intleft=0;
intright=n-1;
intindex=-1;

while(left<=right){
intmid=left+(right-left)/2;
if(arr[mid]==searchElement){
index=mid;
break;
}elseif(arr[mid]<searchElement){
left=mid+1;
}else{
right=mid-1;
}
}
if(index!=-1){
System.out.println(searchElement+"foundatindex"+index);
}else{
System.out.println(searchElement+"notfoundinthearray.");
}
}
}