// 54.
publicclassSelectionSort{
publicstaticvoidmain(String[]args){
int[]arr={64,25,12,22,11};
System.out.println("Originalarray:");
printArray(arr);
selectionSort(arr);
System.out.println("Arrayafterselectionsort:");
printArray(arr);
}
publicstaticvoidselectionSort(int[]arr){
intn=arr.length;
for(inti=0;i<n-1;i++){
intminIndex=i;
for(intj=i+1;j<n;j++){
if(arr[j]<arr[minIndex]){
minIndex=j;
}
}
//Swapthefoundminimumelementwiththefirstelement
inttemp=arr[minIndex];
arr[minIndex]=arr[i];
arr[i]=temp;
}
}
publicstaticvoidprintArray(int[]arr){
for(intvalue:arr){
System.out.print(value+"");
}
System.out.println();

}
}