// 55.
publicclassBubbleSort{
publicstaticvoidmain(String[]args){
int[]arr={64,34,25,12,22,11,90};
System.out.println("Originalarray:");
printArray(arr);
bubbleSort(arr);
System.out.println("Arrayafterbubblesort:");
printArray(arr);
}
publicstaticvoidbubbleSort(int[]arr){
intn=arr.length;
for(inti=0;i<n-1;i++){
booleanswapped=false;
for(intj=0;j<n-i-1;j++){
if(arr[j]>arr[j+1]){
//Swaparr[j]andarr[j+1]
inttemp=arr[j];
arr[j]=arr[j+1];
arr[j+1]=temp;
swapped=true;
}
}
//Ifnotwoelementswereswappedintheinnerloop,thearrayisalreadysorted
if(!swapped){
break;
}
}
}
publicstaticvoidprintArray(int[]arr){
for(intvalue:arr){
System.out.print(value+"");
}
System.out.println();
}
}