// uickSort{
publicstaticvoidmain(String[]args){
int[]arr={10,7,8,9,1,5};
System.out.println("Originalarray:");
printArray(arr);
quickSort(arr,0,arr.length-1);
System.out.println("Arrayafterquicksort:");
printArray(arr);
}
publicstaticvoidquickSort(int[]arr,intlow,inthigh){
if(low<high){
//Partitionthearrayintotwohalves
intpi=partition(arr,low,high);
//Recursivelysorteachhalf
quickSort(arr,low,pi-1);
quickSort(arr,pi+1,high);
}
}
publicstaticintpartition(int[]arr,intlow,inthigh){
intpivot=arr[high];
inti=(low-1);//Indexofsmallerelement
for(intj=low;j<high;j++){
//Ifthecurrentelementissmallerthanorequaltothepivot
if(arr[j]<=pivot){
i++;
//Swaparr[i]andarr[j]
inttemp=arr[i];
arr[i]=arr[j];
arr[j]=temp;
}
}
//Swaparr[i+1]andarr[high](orthepivot)
inttemp=arr[i+1];
arr[i+1]=arr[high];
arr[high]=temp;

returni+1;
}
publicstaticvoidprintArray(int[]arr){
for(intvalue:arr){
System.out.print(value+"");
}
System.out.println();
}
}